spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true

github :
  api-url : https://api.github.com
  token : ${GITHUB_API_TOKEN}

application :
  import-frequency : ${ISSUES_IMPORT_FREQUENCY:60000}











