


spring:

  h2:
    console:
      enabled: true

  datasource:
    name : test
    username : sa
    password:
    url: jdbc:h2:mem:testdb?mode=MySQL


  sql:
    init:
      mode: always
      platform: h2
