spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sawal
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true


